name: Tooling Container

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
    paths:
      - "projects/*"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: yarn test
        working-directory: projects/sdk
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/aardvark-film/tools:${{ github.sha }}
      - name: Image digest
        run: "echo TAG: ghcr.io/aardvark-film/tools:${{ github.sha }} SHA: ${{ steps.docker_build.outputs.digest }}"
